### ISSUE TITLE
"bosh create release --force" fails, pls-jfrogrepo.lss.emc.com unreachable

### ISSUE THREAD

**Issue by 2trc** [emc-cloudfoundry/cassandra-cf-service-boshrelease#2]
bosh create release --force
Syncing blobs...
Total: 0, 0B

You have some blobs that need to be uploaded:
new jetty/jetty-runner-8.1.0.RC5.jar    4.5M
new java/jre-7u55-linux-x64.tar.gz  44.8M
new cassandra/apache-cassandra-1.2.16-bin.tar.gz    16.1M

When ready please run `bosh upload blobs'
Proceeding with dirty blobs as '--force' is given
## Building DEV release

Release artifact cache: /home/user/.bosh/cache
## Building license

Building license...
  Using dev version '4d81eef78735b21bdf9a0bb2951e2dced57524da'
## Building packages

Building jetty...
  Using dev version '99824598f5620a5a49ff87af298fa21b47c620e3'

Building java...
  Using dev version 'a0cd6c6b6bf97b6723655af301a3807cbf2c3456'

Building cassandra...
  No artifact found for cassandra
  Generating...
  Pre-packaging...

> - set -e
> - set -u
> - export HOME=/var/vcap
> - HOME=/var/vcap
> - cd brokers
> - ./gradlew :cassandra:war
>   :spring-service-broker:compileJava
>   :spring-service-broker:processResources
>   :spring-service-broker:classes
>   :spring-service-broker:jar
>   :cassandra:compileJava
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Could not resolve all dependencies for configuration ':cassandra:compile'.
>   
>   > Could not resolve org.springframework.data:spring-data-jpa:1.5.0.RELEASE.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/springframework/data/spring-data-jpa/1.5.0.RELEASE/spring-data-jpa-1.5.0.RELEASE.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve com.github.cloudfoundry-community:nats-client-spring:0.6.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/com/github/cloudfoundry-community/nats-client-spring/0.6/nats-client-spring-0.6.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve org.hibernate:hibernate-core:4.0.1.Final.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/hibernate/hibernate-core/4.0.1.Final/hibernate-core-4.0.1.Final.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve org.hibernate:hibernate-entitymanager:4.0.1.Final.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/hibernate/hibernate-entitymanager/4.0.1.Final/hibernate-entitymanager-4.0.1.Final.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve com.h2database:h2:1.3.175.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/com/h2database/h2/1.3.175/h2-1.3.175.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve commons-io:commons-io:2.4.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/commons-io/commons-io/2.4/commons-io-2.4.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve xerces:xercesImpl:2.11.0.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve xml-apis:xml-apis:1.4.01.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve com.datastax.cassandra:cassandra-driver-core:2.0.1-emc.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/com/datastax/cassandra/cassandra-driver-core/2.0.1-emc/cassandra-driver-core-2.0.1-emc.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve com.codahale.metrics:metrics-core:3.0.2.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/com/codahale/metrics/metrics-core/3.0.2/metrics-core-3.0.2.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve com.google.guava:guava:17.0.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/com/google/guava/guava/17.0/guava-17.0.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve io.netty:netty:3.9.0.Final.
>   > Required by:
>   >     brokers:cassandra:unspecified
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/io/netty/netty/3.9.0.Final/netty-3.9.0.Final.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve org.springframework:spring-context:4.0.2.RELEASE.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/springframework/spring-context/4.0.2.RELEASE/spring-context-4.0.2.RELEASE.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve org.springframework:spring-webmvc:4.0.2.RELEASE.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/springframework/spring-webmvc/4.0.2.RELEASE/spring-webmvc-4.0.2.RELEASE.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve org.springframework:spring-web:4.0.2.RELEASE.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/springframework/spring-web/4.0.2.RELEASE/spring-web-4.0.2.RELEASE.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve org.springframework.security:spring-security-web:3.2.2.RELEASE.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/springframework/security/spring-security-web/3.2.2.RELEASE/spring-security-web-3.2.2.RELEASE.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve org.springframework.security:spring-security-config:3.2.2.RELEASE.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/springframework/security/spring-security-config/3.2.2.RELEASE/spring-security-config-3.2.2.RELEASE.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve com.fasterxml.jackson.core:jackson-core:2.3.2.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/com/fasterxml/jackson/core/jackson-core/2.3.2/jackson-core-2.3.2.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve com.fasterxml.jackson.core:jackson-annotations:2.3.2.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/com/fasterxml/jackson/core/jackson-annotations/2.3.2/jackson-annotations-2.3.2.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve com.fasterxml.jackson.core:jackson-databind:2.3.2.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/com/fasterxml/jackson/core/jackson-databind/2.3.2/jackson-databind-2.3.2.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve org.slf4j:slf4j-api:1.7.6.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve javax.servlet:javax.servlet-api:3.1.0.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve javax.servlet.jsp:jsp-api:2.1.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/javax/servlet/jsp/jsp-api/2.1/jsp-api-2.1.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve javax.servlet:jstl:1.2.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/javax/servlet/jstl/1.2/jstl-1.2.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve org.hibernate:hibernate-validator:5.0.1.Final.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not HEAD 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/hibernate/hibernate-validator/5.0.1.Final/hibernate-validator-5.0.1.Final.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve org.slf4j:jcl-over-slf4j:1.7.6.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/slf4j/jcl-over-slf4j/1.7.6/jcl-over-slf4j-1.7.6.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve org.slf4j:slf4j-log4j12:1.7.6.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.pom'.
>   > pls-jfrogrepo.lss.emc.com
>   > Could not resolve log4j:log4j:1.2.17.
>   > Required by:
>   >     brokers:cassandra:unspecified > brokers:spring-service-broker:0.1
>   > Could not GET 'http://pls-jfrogrepo.lss.emc.com/artifactory/internal/log4j/log4j/1.2.17/log4j-1.2.17.pom'.
>   > pls-jfrogrepo.lss.emc.com
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 12.055 secs
> 'cassandra' pre-packaging failed

**Comment by maazkhan** [comment]
I have changed the maven repo URL to public access URL. It should work now.
