### ISSUE TITLE
PR or cloudfoundry community

### ISSUE THREAD

**Issue by poblin-orange** [emc-cloudfoundry/cassandra-cf-service-boshrelease#4]
Hello,
we made some evolution to your bosh release

Would you accept a PR, or is cloudfoundry community a better place for further community contributions?
thks

**Comment by maazkhan** [comment]
Hi @poblin-orange 

I think CF community will be a better choice, this is no longer being maintained.

**Comment by poblin-orange** [comment]
@maazkhan ok thks :-)
